"""orgIds field name

Revision ID: 14feaf6b8df0
Revises: e8f5209ff685
Create Date: 2019-09-13 13:58:07.768712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '14feaf6b8df0'
down_revision = 'e8f5209ff685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('orgIDs', sa.JSON(), nullable=True))
    op.drop_column('organisation', 'OrgIDs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('OrgIDs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('organisation', 'orgIDs')
    # ### end Alembic commands ###
