"""Add log to scraper

Revision ID: 5c0f09a5b2ef
Revises: 66e2f2bd33e6
Create Date: 2020-05-11 15:00:10.910038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c0f09a5b2ef'
down_revision = '66e2f2bd33e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape', sa.Column('log', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape', 'log')
    # ### end Alembic commands ###
