"""Add identifier table

Revision ID: c0cec5154a74
Revises: 14feaf6b8df0
Create Date: 2019-10-18 10:37:13.524200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0cec5154a74'
down_revision = '14feaf6b8df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identifier',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description_en', sa.String(), nullable=True),
    sa.Column('License', sa.String(), nullable=True),
    sa.Column('access_availableOnline', sa.Boolean(), nullable=True),
    sa.Column('access_exampleIdentifiers', sa.String(), nullable=True),
    sa.Column('access_guidanceOnLocatingIds', sa.String(), nullable=True),
    sa.Column('access_languages', sa.String(), nullable=True),
    sa.Column('access_onlineAccessDetails', sa.String(), nullable=True),
    sa.Column('access_publicDatabase', sa.String(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('coverage', sa.String(), nullable=True),
    sa.Column('data_availability', sa.String(), nullable=True),
    sa.Column('data_dataAccessDetails', sa.String(), nullable=True),
    sa.Column('data_features', sa.String(), nullable=True),
    sa.Column('data_licenseDetails', sa.String(), nullable=True),
    sa.Column('data_licenseStatus', sa.String(), nullable=True),
    sa.Column('deprecated', sa.Boolean(), nullable=True),
    sa.Column('formerPrefixes', sa.String(), nullable=True),
    sa.Column('links_opencorporates', sa.String(), nullable=True),
    sa.Column('links_wikipedia', sa.String(), nullable=True),
    sa.Column('listType', sa.String(), nullable=True),
    sa.Column('meta_lastUpdated', sa.Date(), nullable=True),
    sa.Column('meta_source', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('name_local', sa.String(), nullable=True),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('quality_explained_Availability_API', sa.Integer(), nullable=True),
    sa.Column('quality_explained_Availability_BulkDownload', sa.Integer(), nullable=True),
    sa.Column('quality_explained_Availability_CSVFormat', sa.Integer(), nullable=True),
    sa.Column('quality_explained_Availability_ExcelFormat', sa.Integer(), nullable=True),
    sa.Column('quality_explained_Availability_JSONFormat', sa.Integer(), nullable=True),
    sa.Column('quality_explained_Availability_PDFFormat', sa.Integer(), nullable=True),
    sa.Column('quality_explained_Availability_RDFFormat', sa.Integer(), nullable=True),
    sa.Column('quality_explained_Availability_XMLFormat', sa.Integer(), nullable=True),
    sa.Column('quality_explained_License_ClosedLicense', sa.Integer(), nullable=True),
    sa.Column('quality_explained_License_NoLicense', sa.Integer(), nullable=True),
    sa.Column('quality_explained_License_OpenLicense', sa.Integer(), nullable=True),
    sa.Column('quality_explained_ListType_Local', sa.Integer(), nullable=True),
    sa.Column('quality_explained_ListType_Primary', sa.Integer(), nullable=True),
    sa.Column('quality_explained_ListType_Secondary', sa.Integer(), nullable=True),
    sa.Column('quality_explained_ListType_ThirdParty', sa.Integer(), nullable=True),
    sa.Column('registerType', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('structure', sa.String(), nullable=True),
    sa.Column('subnationalCoverage', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('identifier')
    # ### end Alembic commands ###
