"""add scrape_id to tables

Revision ID: cff2f4e14057
Revises: dbeb90576244
Create Date: 2020-04-15 15:59:57.764377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff2f4e14057'
down_revision = 'dbeb90576244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('scrape_id', sa.String(), nullable=True))
    op.add_column('organisation', sa.Column('spider', sa.String(), nullable=True))
    op.add_column('organisation_links', sa.Column('scrape_id', sa.String(), nullable=True))
    op.add_column('organisation_links', sa.Column('spider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation_links', 'spider')
    op.drop_column('organisation_links', 'scrape_id')
    op.drop_column('organisation', 'spider')
    op.drop_column('organisation', 'scrape_id')
    # ### end Alembic commands ###
