"""add items column

Revision ID: dbeb90576244
Revises: 2c338e0e9ed7
Create Date: 2020-01-12 22:02:01.190847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbeb90576244'
down_revision = '2c338e0e9ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape', sa.Column('items', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape', 'items')
    # ### end Alembic commands ###
