name: Crawl organisations

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DB_URI: ${{ secrets.db_uri }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt-get install python-psycopg2
        sudo apt-get install libpq-dev python3-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: check database upgrade
      run: |
        alembic upgrade head
    - name: run casc
      run: scrapy crawl casc -s DB_URI="$DB_URI"
    - name: run ccni
      run: scrapy crawl ccni -s DB_URI="$DB_URI"
    - name: run gor
      run: scrapy crawl gor -s DB_URI="$DB_URI"
    - name: run grid
      run: scrapy crawl grid -s DB_URI="$DB_URI"
    - name: run hesa
      run: scrapy crawl hesa -s DB_URI="$DB_URI"
    - name: run lae
      run: scrapy crawl lae -s DB_URI="$DB_URI"
    - name: run lani
      run: scrapy crawl lani -s DB_URI="$DB_URI"
    - name: run las
      run: scrapy crawl las -s DB_URI="$DB_URI"
    - name: run nhsods
      run: scrapy crawl nhsods -s DB_URI="$DB_URI"
    - name: run oscr
      run: scrapy crawl oscr -s DB_URI="$DB_URI"
    - name: run pla
      run: scrapy crawl pla -s DB_URI="$DB_URI"
    - name: run rsl
      run: scrapy crawl rsl -s DB_URI="$DB_URI"
    - name: run schools_gias
      run: scrapy crawl schools_gias -s DB_URI="$DB_URI"
    - name: run schools_ni
      run: scrapy crawl schools_ni -s DB_URI="$DB_URI"
    - name: run schools_scotland
      run: scrapy crawl schools_scotland -s DB_URI="$DB_URI"
    - name: run schools_wales
      run: scrapy crawl schools_wales -s DB_URI="$DB_URI"
    - name: run manual_links
      run: scrapy crawl manual_links -s DB_URI="$DB_URI"
